"""
try:
except:
でエラー処理
raise error_name
でエラーを起こせる
"""

